import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import COMMASPACE, formatdate
from email import encoders
import os
import time
import random

def send_mail():
    fromaddr = input('Enter Sender MailID:')
	passwd = input('Enter Sender password:')
    toaddr = input('Enter EmailId:')

    try:
        msg = MIMEMultipart()

        msg['From'] = 'Analyser'
        msg['To'] = 'Human'
        msg['Subject'] = "SQL_QUERY_ANALYSER"

        body = "This is the auto-generated mail.\nIt contains the report generated by the sql_query_analyser."

        msg.attach(MIMEText(body, 'plain'))

        filename = "analyser.csv"
        attachment = open("./analyser.csv", "rb")

        part = MIMEBase('application', 'octet-stream')
        part.set_payload((attachment).read())
        encoders.encode_base64(part)
        part.add_header('Content-Disposition', "attachment; filename= {}".format(filename))

        msg.attach(part)

        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(fromaddr, passwd)
        text = msg.as_string()
        server.sendmail(fromaddr, toaddr, text)
        server.quit()
    except Exception as e:
        print(e)
        return False
    return True
